default:
  db: "org.Hs.eg.db"
  countFile: "data/merged_gene_counts.txt"
  metaDataFile: "data/metadata.csv"
  removeSamples: ""
  gmtForHeatmap: "data/Human_GOBP_AllPathways_no_GO_iea_March_01_2021_symbol.gmt.txt"
  grepGmtTerm: "INTERFERON"
  designlist:
    Status:
      Model: ~ 0 + Status
      Contrast:
        Fibro_vs_Control:
          - Status
          - Fibro
          - Control

